name:                aoc2019day01
version:             0.1.0.0
github:              "djrollins/aoc-2019"
license:             MIT
author:              "Daniel J. Rollins"
maintainer:          "daniel@djrollins.com"
copyright:           "2019 Daniel J. Rollins"


dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: lib
  exposed-modules: Lib

executables:
  day01:
    main:        Day01
    source-dirs: src
    dependencies:
      - aoc2019day01

tests:
  day01test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - aoc2019day01
      - hspec
