name: Run all tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/setup-stack@v1
    - uses: actions/cache@v1.0.3
      with:
        key: ${{ runner.os }}-stack
        path: ~/.stack
    - name: Run tests
      run: stack test
